language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

env:
  - DJANGO=2.2.13
  - DJANGO=3.0.7

install:
  - pip install Django==$DJANGO times da-vinci pillow redis shortuuid
  - sudo apt-get install -qq optipng

script: make test
services: redis
